# Generated by Django 4.2.7 on 2024-12-03 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=0)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_numbers.phonenumber')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
