# Generated by Django 4.2.7 on 2024-12-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0002_phonenumber_status_phonenumber_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callqueue',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='call_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='max_auto_calls',
            field=models.IntegerField(default=5),
        ),
    ]
