# Generated by Django 4.2.7 on 2024-12-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0003_callqueue_manual_phonenumber_call_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callqueue',
            name='manual',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='call_attempts',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='max_auto_calls',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='pending', max_length=20),
        ),
    ]
