# Generated by Django 4.2.7 on 2024-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0004_remove_callqueue_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20),
        ),
    ]
