# Generated by Django 4.2.7 on 2024-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0005_alter_phonenumber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='call_attemptsed',
            field=models.IntegerField(default=0),
        ),
    ]
