# Generated by Django 4.2.7 on 2024-12-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0006_phonenumber_call_attemptsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='call_attemptsed',
        ),
    ]
